In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


# Q4

## Part A

In [ ]:
import numpy as np

In [ ]:
"""
Please define the mentioned matrices and the operations

consider the bellow links:
https://numpy.org/doc/stable/reference/generated/numpy.transpose.html

https://numpy.org/doc/stable/reference/generated/numpy.dot.html

"""

##############################################
############ YOUR CODES GO HERE ##############
arr1 = np.array([[1,2,3], [4,5,6], [7,8,9]], np.int32)
arr2 = np.array([[1], [-1], [1]], np.int32)

# transpose of arr1
transpose_arr1 = np.transpose(arr1)
a = np.linalg.inv(np.dot(transpose_arr1, arr1))
b = np.dot(a, transpose_arr1)
c = np.dot(b, arr2)
d = c+arr1
d
##############################################

array([[0.796875, 1.796875, 2.796875],
       [4.      , 5.      , 6.      ],
       [7.203125, 8.203125, 9.203125]])

## Part B

In [ ]:
def product_windows(A, B):
  res = np.zeros((3,3), int)
  for i in range(len(A)):
    for j in range(len(B)):
      res[i][j] = A[i][j] * B[i][j]
  return res

def window_sliding(A, B):

  """
  In this function you should implement the sliding window method

  Arguments:
    inputs:
      A: a matrix of 3*3 order for treating as the window
      B: a matrix of 5*5 order for treating as the input matrix
    outputs:
      res: resulting matrix of the sliding window 
  """

  ##############################################
  ############ YOUR CODES GO HERE ##############
  res = np.zeros((3,3), int)
  for i in range(0, len(B)-len(A)+1):
    for j in range(0, len(B)-len(A)+1):
      sub_window = B[i:i+len(A), j:j+len(A)]
      p_matrix = product_windows(sub_window, A)
      res[i][j] = np.sum(p_matrix)

  ##############################################

  return res

In [ ]:
A = np.array([[1,1,1], [1,-9,1], [1,1,1]], np.int32)
B = np.array([[1,1,1,1,1], [1,2,2,2,1], [1,2,2,2,1], [1,2,2,2,1], [1,1,1,1,1]], np.int32)
print(window_sliding(A, B))

[[-7 -5 -7]
 [-5 -2 -5]
 [-7 -5 -7]]
